#!/usr/bin/env python3
import sys


def solve(X: int, Y: int, Z: int) -> None:
    if X < 0:
        solve(-X, -Y, -Z)
        return

    if 0 < Y < X:
        if Y < Z:
            print(-1)
        else:
            print(abs(Z) + abs(Z - X))
    else:
        print(X)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    Z = int(next(tokens))  # type: int
    solve(X, Y, Z)


if __name__ == '__main__':
    main()
