#!/usr/bin/env python3
import sys
from typing import List

YES = "Yes"  # type: str
NO = "No"  # type: str


def check(Si: str):
    a, b = Si
    if a not in "HDCS":
        return False
    if b not in "A23456789TJQK":
        return False

    return True


def solve(N: int, S: "List[str]"):
    print(YES if all(check(Si) for Si in S) and len(set(S)) == N else NO)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)


if __name__ == '__main__':
    main()
