#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    H, W, N, h, w = [int(x) for x in input().split()]
    A = [
        [int(x) for x in input().split()]
        for _ in range(H)
    ]
    m00 = [0] * (N + 1)
    for k in range(H):
        for l in range(W):
            if 0 <= k < h and 0 <= l < w:
                continue
            m00[A[k][l]] += 1

    for k0 in range(H - h + 1):
        if k0 != 0:
            for l in range(w):
                m00[A[k0 - 1][l]] += 1
                m00[A[k0 + h - 1][l]] -= 1

        m0 = m00[:]
        for l0 in range(W - w + 1):
            if l0 != 0:
                print(" ", end="")
                for k in range(k0, k0 + h):
                    m0[A[k][l0 - 1]] += 1
                    m0[A[k][l0 + w - 1]] -= 1

            print(sum(v != 0 for v in m0), end="")

        print("")



if __name__ == '__main__':
    main()
