#!/usr/bin/env python3
import sys
from typing import List


def solve(N: int, X: int, P: "List[int]"):
    print(P.index(X) + 1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    P = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, X, P)


if __name__ == '__main__':
    main()
