#!/usr/bin/env python3
import sys
from typing import List


def solve(S: str):
    print(S.rindex("a") + 1 if "a" in S else -1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)


if __name__ == '__main__':
    main()
