#!/usr/bin/env python3
import sys
import itertools

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str) -> str:
    i2col = [3, 2, 4, 1, 3, 5, 0, 2, 4, 6]
    if S[0] != "0":
        return NO
    cs = [0] * 7
    for Si, coli in zip(S, i2col):
        cs[coli] += Si == "1"
    for i, j in itertools.combinations(range(7), 2):
        if j - i <= 1:
            continue
        if cs[i] == 0 or cs[j] == 0:
            continue
        if all(cs[k] == 0 for k in range(i + 1, j)):
            return YES
    return NO


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    print(solve(S))

if __name__ == '__main__':
    main()
