#!/usr/bin/env python3
import sys
from typing import List


def solve(S: str, T: str):
    for i in range(len(S)):
        if S[i] != T[i]:
            print(i + 1)
            return
    print(len(S) + 1)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)


if __name__ == '__main__':
    main()
