name: Update

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
  schedule:
    - cron: "0 20 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master

    - name: Setup Python
      uses: actions/setup-python@v1.2.0

    - name: Install atcoder_git
      run: pip install "git+https://github.com/kurgm/atcoder_git.git@master#egg=atcoder_git"

    - name: Run atcoder_git
      run: atcoder_git --git-user kurgm gogottt2009-hp@yahoo.co.jp . kurgm
    
    - name: Push result
      run: |
        git remote set-url origin "https://kurgm:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git push origin master
