#!/usr/bin/env python3
import sys
from typing import List


def solve(H: int, M: int):
    while True:
        H2 = H // 10 * 10 + M // 10
        M2 = H % 10 * 10 + M % 10
        if 0 <= H2 < 24 and 0 <= M2 < 60:
            print(H, M)
            return
        M += 1
        if M == 60:
            H += 1
            M = 0
        if H == 24:
            H = 0


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    solve(H, M)


if __name__ == '__main__':
    main()
